"""Tests for Vicaya final-note path resolution and validation helpers."""

from __future__ import annotations

from pathlib import Path

from tools import note_checks


def valid_note_text() -> str:
    return """---
tool: "https://github.com/bdhrs/vicaya"
agent: "Codex"
topic: "Patience: release"
canon_refs:
  - "MN 21"
library_refs:
  - "Author: Title"
web_refs:
  - "https://example.com/source"
---
## Question

What does the source material say?

## Findings

The evidence supports a cautious answer.

## Canon Evidence (T1)

- MN 21 gives the relevant example.

## Sources Investigated, Not Used

- None

## Critical Gaps

- None

## Bibliography

- Example source.

---

Generated by Vicaya.

[^1]: Footnote after the footer.
"""


def series_note_text() -> str:
    return valid_note_text().replace(
        """## Canon Evidence (T1)

- MN 21 gives the relevant example.
""",
        """## What the EBTs say about patience

### 1. Patience is praised

> Khantī paramaṃ tapo titikkhā

## What the EBTs don't say about patience

### 1. Patience is not passivity

> Nāhaṃ bhikkhave ...
""",
    )


def issue_codes(text: str) -> set[str]:
    return {issue.code for issue in note_checks.validate_note_text(text)}


def test_resolve_vicaya_prefixed_note_path() -> None:
    vault_path = Path("/tmp/vault")

    resolved = note_checks.resolve_note_path(
        "Vicaya/2099-01-01 - sample.md", vault_path
    )

    assert resolved == vault_path / "Vicaya" / "2099-01-01 - sample.md"


def test_resolve_bare_note_path() -> None:
    vault_path = Path("/tmp/vault")

    resolved = note_checks.resolve_note_path("2099-01-01 - sample.md", vault_path)

    assert resolved == vault_path / "Vicaya" / "2099-01-01 - sample.md"


def test_resolve_absolute_note_path() -> None:
    note_path = Path("/tmp/vault/Vicaya/2099-01-01 - sample.md")

    resolved = note_checks.resolve_note_path(str(note_path), Path("/other/vault"))

    assert resolved == note_path


def test_strip_frontmatter_returns_note_body() -> None:
    stripped = note_checks.strip_frontmatter(valid_note_text())

    assert stripped.startswith("## Question")
    assert "tool:" not in stripped


def test_valid_note_has_no_validation_issues() -> None:
    assert note_checks.validate_note_text(valid_note_text()) == []


def test_missing_frontmatter_is_invalid() -> None:
    text = note_checks.strip_frontmatter(valid_note_text())

    assert "missing-frontmatter" in issue_codes(text)


def test_wrong_tool_is_invalid() -> None:
    text = valid_note_text().replace(
        'tool: "https://github.com/bdhrs/vicaya"',
        'tool: "https://example.com/not-vicaya"',
    )

    assert "invalid-tool" in issue_codes(text)


def test_unquoted_topic_with_colon_space_is_invalid() -> None:
    text = valid_note_text().replace(
        'topic: "Patience: release"',
        "topic: Patience: release",
    )

    assert "invalid-topic" in issue_codes(text)


def test_annotated_web_ref_is_invalid() -> None:
    text = valid_note_text().replace(
        '  - "https://example.com/source"',
        "  - https://example.com/source accessed 2099-01-01",
    )

    assert "invalid-web-ref" in issue_codes(text)


def test_yaml_mapping_style_library_ref_is_invalid() -> None:
    text = valid_note_text().replace(
        '  - "Author: Title"',
        "  - 223: Title",
    )

    assert "invalid-library-ref" in issue_codes(text)


def test_quoted_library_ref_with_colon_space_is_valid() -> None:
    text = valid_note_text().replace(
        '  - "Author: Title"',
        '  - "223: Title"',
    )

    assert "invalid-library-ref" not in issue_codes(text)


def test_rejected_citation_tag_is_invalid() -> None:
    text = valid_note_text().replace(
        "The evidence supports a cautious answer.",
        "The evidence supports a cautious answer. [REJECTED]",
    )

    assert "rejected-citation" in issue_codes(text)


def test_missing_required_section_is_invalid() -> None:
    text = valid_note_text().replace("## Critical Gaps", "## Remaining Questions")

    assert "missing-section" in issue_codes(text)


def test_canon_evidence_requires_canon_ref() -> None:
    text = valid_note_text().replace('  - "MN 21"\n', "")

    assert "missing-canon-ref" in issue_codes(text)


def test_standard_note_missing_canon_evidence_warns() -> None:
    text = valid_note_text().replace(
        "## Canon Evidence (T1)\n\n- MN 21 gives the relevant example.\n", ""
    )

    issues = note_checks.validate_note_text(text)

    assert [(i.code, i.severity) for i in issues] == [("missing-section", "warning")]


def test_series_note_without_canon_evidence_is_clean() -> None:
    assert note_checks.validate_note_text(series_note_text()) == []


def test_series_heading_variants_are_recognized() -> None:
    base = valid_note_text().replace(
        "## Canon Evidence (T1)\n\n- MN 21 gives the relevant example.\n", ""
    )
    for heading in (
        "## Section 1 — What the EBTs Say About Vipassanā",
        "## Section 2 — What the EBTs Do *Not* Say About Vipassanā",
        "## 1. What the suttas say about emptiness",
    ):
        text = base.replace(
            "The evidence supports a cautious answer.\n",
            f"The evidence supports a cautious answer.\n\n{heading}\n\n> Quote.\n",
        )

        assert note_checks.validate_note_text(text) == []


def test_series_note_missing_findings_errors_with_hint() -> None:
    text = series_note_text().replace(
        "## Findings\n\nThe evidence supports a cautious answer.\n", ""
    )

    issues = [
        issue
        for issue in note_checks.validate_note_text(text)
        if issue.code == "missing-section"
    ]

    assert len(issues) == 1
    assert issues[0].severity == "error"
    assert "## Findings" in issues[0].message
    assert "fixed-format/series" in issues[0].message


def test_early_footnote_definition_is_invalid() -> None:
    text = valid_note_text().replace(
        "## Bibliography",
        "[^1]: Early footnote.\n\n## Bibliography",
    )

    assert "invalid-footnote-placement" in issue_codes(text)
